# Generated by Django 4.2 on 2024-12-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='list_data',
            new_name='list_date',
        ),
    ]
